@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component diagram backend Triptop

Container_Boundary(backend, "Backend") {
    Component(bouwsteenController, "Bouwsteen controller", "component")
    Component(bouwsteenService, "Bouwsteen service", "component")
    Component(bouwsteenRepository, "Bouwsteen repository", "component")

    Component(authService, "Authenticatie service", "component")

    Component(adviesController, "Advies controller", "component")
    Component(adviesService, "Advies service", "component")
    Component(adviesRepository, "Advies service", "component")
}

Rel_D(bouwsteenController, bouwsteenService, "Gebruikt")
Rel_D(bouwsteenService, bouwsteenRepository, "Gebruikt")
Rel_D(bouwsteenController, authService, "Gebruikt")
Rel_D(adviesController, authService, "Gebruikt")
Rel_D(adviesController, adviesService, "Gebruikt")
Rel_D(adviesService, adviesRepository, "Gebruikt")

Container(frontend, "Frontend", "React")
Container(database, "Database", "Microsoft SQL Server")

System_Ext(centraleIdentiteitProvider, "Centrale identiteit provider (Google, Microsoft, AirBnb)", "Authenticeert gebruikers")
System_Ext(treinProvider, "Treinreis provider (NS, Deutsche Bahn)", "Biedt treinreizen")
System_Ext(vluchtProvider, "Vlucht provider (KLM)", "Biedt vluchten")
System_Ext(voedselProvider, "Voedsel provider (Takeaway, Eet.nu)", Biedt voedsel)
System_Ext(activiteitProvider, "Activiteit provider (GetYourGuide, Tripadvisor)", "Biedt activiteiten")
System_Ext(accommodatieProvider, "accommodatie provider (Booking.com, Airbnb)", "Biedt accommodaties")
System_Ext(autoverhuurProvider, "Autoverhuur provider (Sixt, Hertz)", "Biedt autoverhuur")

Rel_D(frontend, bouwsteenController, "Wijzigt en bekijkt trip", "JSON/HTTPS")
Rel_D(frontend, adviesController, "Leest en schrijft advies", "JSON/HTTPS")

Rel_D(authService, centraleIdentiteitProvider, "Verifieert authenticatie", "JSON/HTTPS")
Rel_D(bouwsteenRepository, database, "Lezen en schrijven", "SQL")
Rel_D(adviesRepository, database, "Lezen en schrijven", "SQL")

Rel_L(bouwsteenService, treinProvider, "Vraagt en stuurt data", "JSON/HTTPS")
Rel_L(bouwsteenService, vluchtProvider, "Vraagt en stuurt data", "JSON/HTTPS")
Rel_L(bouwsteenService, voedselProvider, "Vraagt en stuurt data", "JSON/HTTPS")
Rel_L(bouwsteenService, activiteitProvider, "Vraagt en stuurt data", "JSON/HTTPS")
Rel_L(bouwsteenService, accommodatieProvider, "Vraagt en stuurt data", "JSON/HTTPS")
Rel_L(bouwsteenService, autoverhuurProvider, "Vraagt en stuurt data", "JSON/HTTPS")

LAYOUT_WITH_LEGEND()

@enduml