@startuml "Triptop Dynamic Container Diagram"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

title Dynamic Container diagram voor Triptop - Reisplanning

SHOW_PERSON_OUTLINE()

Person(reiziger, "Reiziger", "Stelt reis samen")
Person(reisagent, "Reisagent", "Biedt tweedelijns support")

System_Boundary(triptop_system, "Triptop") {
  Container(frontend, "Web Application", "React", "Biedt reisplanning UI")
  Container(backend, "Backend", "Spring Boot", "Beheert reizen")
  Container(db, "Database", "Microsoft SQL Server", "Slaat reisplannen op")
}

System_Ext(centrale_identity_provider, "Centrale identity provider (Google, Microsoft, AirBnb)", "Identificeert gebruikers")
System_Ext(overige_providers, "Overige providers")

Rel_D(reiziger, frontend, "Plant reis")
Rel_D(frontend, centrale_identity_provider, "Authenticeert", "JSON/HTTPS")
Rel(centrale_identity_provider, frontend, "Geeft token","JSON/HTTPS")
Rel_L(frontend, backend, "Vraagt informatie", "JSON/HTTPS")
Rel_D(backend, centrale_identity_provider, "Identificeert gebruikers", "JSON/HTTPS")
Rel_D(backend, overige_providers, "Vraagt Data", "JSON/HTTPS")
Rel_U(overige_providers, backend, "Geeft data terug","JSON/HTTPS")
Rel_L(backend, db, "Slaat reisplannen op", "SQL")
Rel_D(reiziger, frontend, "Vraagt advies")
Rel_D(reisagent, frontend, "Geeft advies")
Rel_D(reiziger, frontend, "Boekt reis")
Rel_L(frontend, backend, "Boekt reis", "JSON/HTTPS")
Rel_D(backend, overige_providers, "Boekt reis", "JSON/HTTPS")





@enduml