@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

Person(Reiziger, "Reiziger", "Plannen en boeken van een reis")

System_Boundary(s1, Triptop){
Container(webApp,"Webapplicatie","React", "De applicatie waar de klant zijn reis kan plannen")
Container(Backend, "Backend", "Java Spring-Boot", "Voert logica uit")
Container(Database, "Database", "Microsoft Sql Server", "Opslaan van data")
}



Rel(Reiziger, webApp, "Voert inloggegevens in")
Rel(webApp, Backend, "Stuurt inlogGegevens door")
Rel(Backend, Database, "Vraagt gebruikersinformatie op")
Rel(Backend, Backend, "Valideer inloggegevens")
Rel(Backend, webApp, "Stuurt Token terug")
@enduml