@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

title Dynamic Container diagram voor Triptop - Inloggen

Person(reiziger, "Reiziger", "Stelt reis samen")

System_Boundary(triptop_system, "Triptop") {
  Container(frontend, "Frontend", "React", "Biedt reisplanning UI")
}

System_Ext(centrale_identity_provider, "Centrale identity provider (Google, Microsoft, AirBnb)", "Identificeert gebruikers")

Rel_D(reiziger, frontend, "Voert inloggegevens in")
Rel_D(frontend, centrale_identity_provider, "Authenticeert")
Rel_D(centrale_identity_provider, frontend, "Geeft token terug")

LAYOUT_WITH_LEGEND()

@enduml