@startuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
SHOW_PERSON_OUTLINE()

title C4-Context Diagram - Context diagram voor Triptop-applicatie.

Person(reiziger, "Reiziger", "Een gebruiker die zijn eigen reis samenstelt en beheert.")\

Person(reisagent, "Reisagent", "Een reisagent die voor een reiziger een reis samensteld en boekt.")\


    System(triptop_app, "Triptop Web Applicatie", "Online platform voor het plannen en boeken van reizen.")
    System_Ext(triptop_identity, "Identity Provider  (Google, Microsoft, AirBnb, etc.)", "Externe authenticatiedienst")
    System_Ext(food, "foodprovider (Takeaway, eet.nu)", "Biedt eetmogelijkheden aan ")
    System_Ext(travel, "travelprovider (ns,deutschebahn, klm, sixt)", "Biedt vervoersmogenlijkheden aan")
    System_Ext(excursion, "Excursionprovider (Tripadvisor, GetYourGuide)", "Biedt excurties aan")
    System_Ext(overnight, "Overnightprovider (Booking, airBnb)", "Boekt mogelijke overnachtingen aan")


Rel(reiziger, triptop_app, "Boekt reis ")


Rel(triptop_app, triptop_identity, "Verifieert identiteit via")
Rel(triptop_app, food, "Haalt eet en drink opties op via")
Rel(triptop_app, travel, "Haalt vervoersmogenljkheden op via")
Rel(triptop_app, excursion, "Haalt excursiemogenlijkheden op via")
Rel(triptop_app, overnight, "Haalt overnachting mogelijkheden op via")
@enduml
