@startuml
actor reiziger
participant "TravelController" as Controller
participant "TravelService" as Service
participant "TravelAdapter" as Adapter
participant "Externe Api's" as API

reiziger -> Controller: getTravelData()
Controller -> Service: getTravelData(locationStart, locationEnd, travelType)
Service ->  Adapter: getTravelData(locationStart,locationEnd,travelType)
Adapter -> API : GetRoute(locationStart, locationEnd)
API --> Adapter: route
Adapter --> Service: route
Service --> Controller: route
Controller --> reiziger: route


@enduml