@startuml
'https://plantuml.com/class-diagram
title Code Diagram Backend Adapter voor triptop

class TravelController{

}
class TravelService{
    getRoute(treinNaam: String): void
}
class TreinAdapterFactory
{
    getTreinAdapter(treinNaam: String): ITreinAdapter
}

interface ITreinAdapter{
   getRoute(): void
}
class DirectionsAdapter{
 getRoute(): void
}
class DeutscheBahnAdapter{
  getRoute(): void
}



TravelController --> TravelService
TravelService --> ITreinAdapter
TravelService ..> TreinAdapterFactory
DirectionsAdapter..|> ITreinAdapter
DeutscheBahnAdapter ..|> ITreinAdapter
TreinAdapterFactory ..> ITreinAdapter

node DeutscheBahnAPI as "DeutscheBahn"{
   }

node DirectionsApi as "Directions"{
   }

DirectionsAdapter -- DirectionsApi
DeutscheBahnAdapter -- DeutscheBahnAPI
@enduml