@startuml
'https://plantuml.com/class-diagram
title Code Diagram Backend Adapter voor triptop


class TravelService{
    getTravelData(locationStart: String, locationEnd: String, travelType: String): void
}

interface ITravelAdapter{
   getRoute(): void
}
class DirectionsAdapter{
 getRoute(): void
}
class DeutscheBahnAdapter{
  getRoute(): void
}




TravelService --> ITravelAdapter

DirectionsAdapter..|> ITravelAdapter
DeutscheBahnAdapter ..|> ITravelAdapter


node DeutscheBahnAPI as "DeutscheBahnApi"{
   }

node DirectionsApi as "DirectionsApi"{
   }

DirectionsAdapter -- DirectionsApi
DeutscheBahnAdapter -- DeutscheBahnAPI
@enduml