@startuml
actor reiziger
participant "TravelController" as Controller
participant "TravelService" as Service
participant "TravelAdapter" as Adapter


reiziger -> Controller: getTravelData(locationStart, locationEnd, travelType)
Controller -> Service: getTravelData(locationStart, locationEnd, travelType)
Service ->  Adapter: getTravelData(locationStart,locationEnd,travelType)
Adapter --> Service: route
Service --> Controller: route
Controller --> reiziger: route


@enduml