@startuml

title Code diagram backend externe service Triptop

class Flight <<record>> {
    -departureTime : DateTime
    -arrivalTime : DateTime
    +departureTime() : DateTime
    +arrivalTime() : DateTime
}

class Car <<record>> {
    -brand : String
    +brand() : String
}

class BuildingBlockService {
    +book(BuildingBlock buildingBlock) : boolean
}

class FlightService {
    +book(BuildingBlock flight) : boolean
}

class CarRentalService {
    +book(BuildingBlock car) : boolean
}

interface BuildingBlock {
    +price() : Double
}

BuildingBlockService --> FlightService
BuildingBlockService --> CarRentalService
BuildingBlockService --> Car
BuildingBlockService --> Flight
Flight ..|> BuildingBlock
Car ..|> BuildingBlock


node "KLM API" as KLM {
}

node "Hertz API" as Hertz {
}

FlightService -- KLM
CarRentalService -- Hertz

@enduml