@startuml

class Advice {
    + generateStrategy(adviceStrategy)
}

class AdviceStrategy {
    generateStrategy()
}

class SimpleAdviceStrategy{

}

class AdvancedAdviceStrategy{

}

Advice --> AdviceStrategy
SimpleAdviceStrategy..|>AdviceStrategy
AdvancedAdviceStrategy..|>AdviceStrategy
@enduml